### ISSUE TITLE
UX issue

### ISSUE THREAD

**Issue by bendqh** [brainstormforce/astra-bulk-edit#9]
I work with content management systems since 2009... I have much experience with these. I feel there is a slight UX problem finding ABE and its options:

I installed and activated "Astra Bulk Edit" but I didn't easily find where to operate it in my WordPress menu.

WP admin > Themes > Astra options OR WP admin > Settings, doesn't seem to cover it.

I went to the documentation and saw a screenshot aiming me to "pages" but under "pages" (RTL-Hebrew) I saw nothing.

I kept reading the docs and saw:

> 2.Open the bulk edit option for pages/posts. You will see the Astra Meta

But I don't understand where I should open this.

Thus AFN I miss where to change all pages created with Elementor to be such with **Elementor full-width template** but I might need to do so manually.

Maybe the docs should be changed to be a bit more clear.

**Comment by sujaypawar** [comment]
Thanks for the feedback @bendqh 

For the documentation, we have a video embedded on our plugin page that walks through how plugin works: https://wordpress.org/plugins/astra-bulk-edit/

We have a written documentation on our website where we have added a quick GIF as well:
https://wpastra.com/docs/bulk-edit-astra-meta-settings-multiple-pages-posts/

But appreciate your feedback. We will try to improve it further with a quick notice as soon as the plugin is activated.

**Comment by bendqh** [comment]
Thanks !

**Comment by sujaypawar** [comment]
Thanks a ton for review @bendqh

**Comment by sujaypawar** [comment]
If you don't mind, a review for the Astra theme will be helpful as well :) 

https://wordpress.org/support/theme/astra/reviews/?filter=5

**Comment by bendqh** [comment]
@sujaypawar  I just did so.
